apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  persistentVolumeReclaimPolicy: Retain  # PV 삭제 시 데이터 유지 정책
  nfs:  # NFS 또는 다른 스토리지 제공자 구성 (필요에 따라)
    path: /mnt/data
    server: 192.168.1.1  # NFS 서버 주소 예시


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-primary-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}