apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
type: Opaque
data:
  user: {{ .Values.secrets.user | b64enc }}
  password: {{ .Values.secrets.password | b64enc }}
  rootPassword: {{ .Values.secrets.rootPassword | b64enc }}
