apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.rollout.strategy | nindent 4 }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          securityContext: 
            runAsUser: {{.Values.securityContext.runAsUser}}
            runAsGroup: {{.Values.securityContext.runAsGroup}}
            allowPrivilegeEscalation: {{.Values.securityContext.allowPrivilegeEscalation}}
            readOnlyRootFilesystem: {{.Values.securityContext.readOnlyRootFilesystem}}
            capabilities:
              drop:
                - ALL
      volumes:
        - name: tmp-volume
          emptyDir: {}

